services:
  db:
    image: postgres:14.0
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: medicdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
