services:
  medic-api:
    image: r4zu91/medic-api
    container_name: medic-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm start:dev
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  postgres:
    image: postgres:14.0
    container_name: medicdb
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
