services:
  medic-api:
    image: r4zu91/medic-api
    container_name: medic-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DB_HOST}
    ports:
      - '${PORT}:${PORT}'

  db:
    image: postgres:14.0
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: medicdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
